backend:
  name: git-gateway
  branch: main
media_folder: static/assets
public_folder: /src/images/featured
collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime, format: MMM DD YYYY }
      - { name: title, label: Title }
      - {name: description, label: Description}
      - {
        label: "Featured Image",
         name: "thumb", 
         widget: "image"
        }
      - { name: body, label: Body, widget: markdown }